//   list of surahs
export const surah = [
  {
    labelEng: 'Al-Fatihah',
    labelAra: 'سُوْرَۃُ الفَاتِحَة',
    subTitle: 'The Opening',
    pageStart: 1,
    pageEnd: 1,
    madani: 0,
  },
  {
    labelEng: 'Al-Baqarah',
    labelAra: 'سُوْرَۃُ البَقَرَة',
    subTitle: 'The Cow',
    pageStart: 2,
    pageEnd: 49,
    madani: 1,
  },
  {
    labelEng: 'Aali Imran',
    labelAra: 'سُوْرَۃ آلِ عِمْرَان',
    subTitle: 'The Family of Imran',
    pageStart: 50,
    pageEnd: 76,
    madani: 1,
  },
  {
    labelEng: 'An-Nisaa',
    labelAra: 'سُوْرَۃُ النِّسَاء',
    subTitle: 'The Women',
    pageStart: 77,
    pageEnd: 106,
    madani: 1,
  },
  {
    labelEng: 'Al-Ma’idah',
    labelAra: 'سُوْرَۃُ المَائِدَة',
    subTitle: 'The Table',
    pageStart: 106,
    pageEnd: 127,
    madani: 1,
  },
  {
    labelEng: 'Al-An’am',
    labelAra: 'سُوْرَۃُ الأَنْعَام',
    subTitle: 'The Cattle',
    pageStart: 128,
    pageEnd: 150,
    madani: 0,
  },
  {
    labelEng: 'Al-A’raf',
    labelAra: 'سُوْرَۃُ الأَعْرَاف',
    subTitle: 'The Heights',
    pageStart: 151,
    pageEnd: 176,
    madani: 0,
  },
  {
    labelEng: 'Al-Anfal',
    labelAra: 'سُوْرَۃُ الأَنْفَال',
    subTitle: 'The Spoils of War',
    pageStart: 177,
    pageEnd: 186,
    madani: 1,
  },
  {
    labelEng: 'At-Taubah',
    labelAra: 'سُوْرَۃُ التَّوْبَة',
    subTitle: 'The Repentance',
    pageStart: 187,
    pageEnd: 207,
    madani: 1,
  },
  {
    labelEng: 'Yunus',
    labelAra: 'سُوْرَۃ يُونُس',
    subTitle: 'Yunus',
    pageStart: 208,
    pageEnd: 221,
    madani: 0,
  },
  {
    labelEng: 'Hud',
    labelAra: 'سُوْرَۃ هُود',
    subTitle: 'Hud',
    pageStart: 221,
    pageEnd: 235,
    madani: 0,
  },
  {
    labelEng: 'Yusuf',
    labelAra: 'سُوْرَۃ يُوسُف',
    subTitle: 'Yusuf',
    pageStart: 235,
    pageEnd: 248,
    madani: 0,
  },
  {
    labelEng: 'Ar-Ra’d',
    labelAra: 'سُوْرَۃ الرَّعْد',
    subTitle: 'the Thunder',
    pageStart: 249,
    pageEnd: 255,
    madani: 1,
  },
  {
    labelEng: 'Ibrahim',
    labelAra: 'سُوْرَۃُ إِبْرَاهِيم',
    subTitle: 'Ibrahim',
    pageStart: 255,
    pageEnd: 261,
    madani: 0,
  },
  {
    labelEng: 'Al-Hijr',
    labelAra: 'سُوْرَۃُ الحِجْر',
    subTitle: 'The Rocky Tract',
    pageStart: 262,
    pageEnd: 267,
    madani: 0,
  },
  {
    labelEng: 'An-Nahl',
    labelAra: 'سُوْرَۃُ النَّحْل',
    subTitle: 'The Bees',
    pageStart: 267,
    pageEnd: 281,
    madani: 0,
  },
  {
    labelEng: 'Al-Israa',
    labelAra: 'سُوْرَۃُ الإِسْرَاء',
    subTitle: 'The Night Journey',
    pageStart: 282,
    pageEnd: 293,
    madani: 0,
  },
  {
    labelEng: 'Al-Kahf',
    labelAra: 'سُوْرَۃ الكَهْف',
    subTitle: 'The Cave',
    pageStart: 293,
    pageEnd: 304,
    madani: 0,
  },
  {
    labelEng: 'Maryam',
    labelAra: 'سُوْرَۃ مَرْيَم',
    subTitle: 'Maryam',
    pageStart: 305,
    pageEnd: 312,
    madani: 0,
  },
  {
    labelEng: 'Ta-Ha',
    labelAra: 'سُوْرَۃ طٰهٰ',
    subTitle: 'Ta-Ha',
    pageStart: 312,
    pageEnd: 321,
    madani: 0,
  },
  {
    labelEng: 'Al-Anbiyaa',
    labelAra: 'سُوْرَۃُ الأَنْبِيَاء',
    subTitle: 'The Prophets',
    pageStart: 322,
    pageEnd: 331,
    madani: 0,
  },
  {
    labelEng: ' Al-Haj',
    labelAra: 'سُوْرَۃ الحَجّ',
    subTitle: 'The Pilgrimage',
    pageStart: 332,
    pageEnd: 341,
    madani: 1,
  },
  {
    labelEng: 'Al-Mu’minun',
    labelAra: 'سُوْرَۃُ المُؤْمِنُون',
    subTitle: 'The Believers',
    pageStart: 342,
    pageEnd: 349,
    madani: 0,
  },
  {
    labelEng: 'An-Nur',
    labelAra: 'سُوْرَۃ النُّور',
    subTitle: 'The Light',
    pageStart: 350,
    pageEnd: 359,
    madani: 1,
  },
  {
    labelEng: 'Al-Furqan',
    labelAra: 'سُوْرَۃ الفُرْقَان',
    subTitle: 'The Criterion',
    pageStart: 359,
    pageEnd: 366,
    madani: 0,
  },
  {
    labelEng: 'Ash-Shu’ara’ ',
    labelAra: 'سُوْرَۃُ الشُّعَرَاء',
    subTitle: 'The Poets',
    pageStart: 367,
    pageEnd: 376,
    madani: 0,
  },
  {
    labelEng: 'An-Naml',
    labelAra: 'سُوْرَۃُ النَّمْل',
    subTitle: 'The Ants',
    pageStart: 377,
    pageEnd: 385,
    madani: 0,
  },
  {
    labelEng: 'Al-Qasas',
    labelAra: 'سُوْرَۃُ القَصَص',
    subTitle: 'The Stories',
    pageStart: 385,
    pageEnd: 396,
    madani: 0,
  },
  {
    labelEng: 'Al-Ankabut',
    labelAra: 'سُوْرَۃُ العَنْكَبُوت',
    subTitle: 'The Spider',
    pageStart: 396,
    pageEnd: 404,
    madani: 0,
  },
  {
    labelEng: 'Ar-Rum',
    labelAra: 'سُوْرَۃ الرُّوم',
    subTitle: 'The Romans',
    pageStart: 404,
    pageEnd: 410,
    madani: 0,
  },
  {
    labelEng: 'Luqman',
    labelAra: 'سُوْرَۃ لُقْمَان',
    subTitle: 'Luqman',
    pageStart: 411,
    pageEnd: 414,
    madani: 0,
  },
  {
    labelEng: 'As-Sajdah',
    labelAra: 'سُوْرَۃُ السَّجْدَة',
    subTitle: 'The Prostration',
    pageStart: 415,
    pageEnd: 417,
    madani: 0,
  },
  {
    labelEng: 'Al-Ahzab',
    labelAra: 'سُوْرَۃُ الأَحْزَاب',
    subTitle: 'The Combined Forces',
    pageStart: 418,
    pageEnd: 427,
    madani: 1,
  },
  {
    labelEng: 'Saba',
    labelAra: 'سُوْرَۃ سَبَأ',
    subTitle: 'The Sabeans',
    pageStart: 428,
    pageEnd: 434,
    madani: 0,
  },
  {
    labelEng: 'Al-Fatir',
    labelAra: 'سُوْرَۃ فَاطِر',
    subTitle: 'The Originator',
    pageStart: 434,
    pageEnd: 440,
    madani: 0,
  },
  {
    labelEng: 'Ya-Sin',
    labelAra: 'سُوْرَۃ يٰس',
    subTitle: 'Ya-Sin',
    pageStart: 440,
    pageEnd: 445,
    madani: 0,
  },
  {
    labelEng: 'As-Saffah',
    labelAra: 'سُوْرَۃُ الصَّافَّات',
    subTitle: 'Those Ranges in Ranks',
    pageStart: 446,
    pageEnd: 452,
    madani: 0,
  },
  {
    labelEng: 'Sad',
    labelAra: 'سُوْرَۃ ص',
    subTitle: 'Sad',
    pageStart: 452,
    pageEnd: 458,
    madani: 0,
  },
  {
    labelEng: 'Az-Zumar',
    labelAra: 'سُوْرَۃُ الزُّمَر',
    subTitle: 'The Groups',
    pageStart: 458,
    pageEnd: 467,
    madani: 0,
  },
  {
    labelEng: "Al Mo'minoun",
    labelAra: 'سُوْرَۃ غَافِر',
    subTitle: 'The Believer',
    pageStart: 467,
    pageEnd: 476,
    madani: 0,
  },
  {
    labelEng: 'Hamim Sijdah',
    labelAra: 'فُصِّلَتْ',
    subTitle: 'Hamin Sijdah',
    pageStart: 477,
    pageEnd: 482,
    madani: 0,
  },
  {
    labelEng: 'Ash-Shura',
    labelAra: 'سُوْرَۃُ الشُّورىٰ',
    subTitle: 'The Consultation',
    pageStart: 483,
    pageEnd: 489,
    madani: 0,
  },
  {
    labelEng: 'Az-Zukhruf',
    labelAra: 'سُوْرَۃُ الزُّخْرُف',
    subTitle: 'The Gold',
    pageStart: 489,
    pageEnd: 495,
    madani: 0,
  },
  {
    labelEng: 'Ad-Dukhan',
    labelAra: 'سُوْرَۃ الدُّخَان',
    subTitle: 'The Smoke',
    pageStart: 496,
    pageEnd: 498,
    madani: 0,
  },
  {
    labelEng: 'Al-Jathiyah',
    labelAra: 'سُوْرَۃ الجَاثِيَة',
    subTitle: 'The Kneeling',
    pageStart: 499,
    pageEnd: 502,
    madani: 0,
  },
  {
    labelEng: 'Al-Ahqaf',
    labelAra: 'سُوْرَۃُ الأَحْقَاف',
    subTitle: 'The Valley',
    pageStart: 502,
    pageEnd: 506,
    madani: 0,
  },
  {
    labelEng: 'Muhammad',
    labelAra: 'سُوْرَۃ مُحَمَّد',
    subTitle: 'Muhammad',
    pageStart: 507,
    pageEnd: 510,
    madani: 1,
  },
  {
    labelEng: 'Al-Fat’h',
    labelAra: 'سُوْرَۃُ الفَتْح',
    subTitle: 'The Victory',
    pageStart: 511,
    pageEnd: 515,
    madani: 1,
  },
  {
    labelEng: 'Al-Hujurat',
    labelAra: 'سُوْرَۃُ الحُجُرَات',
    subTitle: 'The Dwellings',
    pageStart: 515,
    pageEnd: 517,
    madani: 1,
  },
  {
    labelEng: 'Qaf',
    labelAra: 'سُوْرَۃ ق',
    subTitle: 'Qaf',
    pageStart: 518,
    pageEnd: 520,
    madani: 0,
  },
  {
    labelEng: 'adh-Dhariyat',
    labelAra: 'سُوْرَۃُ الذَّارِيَات',
    subTitle: 'The Scatterers',
    pageStart: 520,
    pageEnd: 523,
    madani: 0,
  },
  {
    labelEng: 'at-Tur',
    labelAra: 'سُوْرَۃ الطُّور',
    subTitle: 'The Mount',
    pageStart: 523,
    pageEnd: 525,
    madani: 0,
  },
  {
    labelEng: 'an-Najm',
    labelAra: 'سُوْرَۃُ النَّجْم',
    subTitle: 'The Star',
    pageStart: 526,
    pageEnd: 528,
    madani: 0,
  },
  {
    labelEng: 'al-Qamar',
    labelAra: 'سُوْرَۃُ القَمَر',
    subTitle: 'The Moon',
    pageStart: 528,
    pageEnd: 531,
    madani: 0,
  },
  {
    labelEng: 'ar-Rahman',
    labelAra: 'سُوْرَۃ الرَّحْمَٰن',
    subTitle: 'The All-merciful',
    pageStart: 531,
    pageEnd: 534,
    madani: 1,
  },
  {
    labelEng: "al-Waqi'ah",
    labelAra: 'سُوْرَۃُ الوَاقِعَة',
    subTitle: 'The Terror',
    pageStart: 534,
    pageEnd: 537,
    madani: 0,
  },
  {
    labelEng: 'al-Hadid',
    labelAra: 'سُوْرَۃُ الحَدِيد',
    subTitle: 'Iron',
    pageStart: 537,
    pageEnd: 541,
    madani: 1,
  },
  {
    labelEng: 'Al-Mujadilah',
    labelAra: 'سُوْرَۃُ المُجَادِلَة',
    subTitle: 'The Reasoning',
    pageStart: 542,
    pageEnd: 545,
    madani: 1,
  },
  {
    labelEng: 'Al-Hashr',
    labelAra: 'سُوْرَۃُ الحَشْر',
    subTitle: 'The Gathering',
    pageStart: 545,
    pageEnd: 548,
    madani: 1,
  },
  {
    labelEng: 'Al-Mumtahanah',
    labelAra: 'سُوْرَۃُ المُمْتَحَنَة',
    subTitle: 'The Tested',
    pageStart: 549,
    pageEnd: 551,
    madani: 1,
  },
  {
    labelEng: 'As-Saf',
    labelAra: 'سُوْرَۃُ الصَّفّ',
    subTitle: 'The Row',
    pageStart: 551,
    pageEnd: 552,
    madani: 1,
  },
  {
    labelEng: 'Al-Jum’ah',
    labelAra: 'سُوْرَۃُ الجُمُعَة',
    subTitle: 'Friday',
    pageStart: 553,
    pageEnd: 554,
    madani: 1,
  },
  {
    labelEng: 'Al-Munafiqun',
    labelAra: 'سُوْرَۃُ المُنَافِقُون',
    subTitle: 'The Hypocrites',
    pageStart: 554,
    pageEnd: 555,
    madani: 1,
  },
  {
    labelEng: 'At-Taghabun',
    labelAra: 'سُوْرَۃُ التَّغَابُن',
    subTitle: 'The Loss & Gain',
    pageStart: 556,
    pageEnd: 557,
    madani: 1,
  },
  {
    labelEng: 'At-Talaq',
    labelAra: 'سُوْرَۃُ الطَّلَاق',
    subTitle: 'The Divorce',
    pageStart: 558,
    pageEnd: 559,
    madani: 1,
  },
  {
    labelEng: '6At-Tahrim',
    labelAra: 'سُوْرَۃُ التَّحْرِيم',
    subTitle: 'The Prohibition',
    pageStart: 560,
    pageEnd: 561,
    madani: 1,
  },
  {
    labelEng: 'Al-Mulk',
    labelAra: 'سُوْرَۃُ المُلْك',
    subTitle: 'The Kingdom',
    pageStart: 562,
    pageEnd: 564,
    madani: 0,
  },
  {
    labelEng: 'Al-Qalam',
    labelAra: 'سُوْرَۃ القَلَم',
    subTitle: 'The Pen',
    pageStart: 564,
    pageEnd: 566,
    madani: 0,
  },
  {
    labelEng: 'Al-Haqqah',
    labelAra: 'سُوْرَۃ الحَاقَّة',
    subTitle: 'The Inevitable',
    pageStart: 566,
    pageEnd: 568,
    madani: 0,
  },
  {
    labelEng: 'Al-Ma’arij',
    labelAra: 'سُوْرَۃُ المَعَارِج',
    subTitle: 'The Elevated Passages',
    pageStart: 568,
    pageEnd: 570,
    madani: 0,
  },
  {
    labelEng: 'Nuh',
    labelAra: 'سُوْرَۃ نُوح',
    subTitle: 'Nuh',
    pageStart: 570,
    pageEnd: 571,
    madani: 0,
  },
  {
    labelEng: 'Al-Jinn',
    labelAra: 'سُوْرَۃُ الجِنّ',
    subTitle: 'The Jinn',
    pageStart: 572,
    pageEnd: 573,
    madani: 0,
  },
  {
    labelEng: 'Al-Muzammil',
    labelAra: 'سُوْرَۃُ المُزَّمِّل',
    subTitle: 'The Wrapped',
    pageStart: 574,
    pageEnd: 575,
    madani: 0,
  },
  {
    labelEng: 'Al-Mudaththir',
    labelAra: 'سُوْرَۃُ المُدَّثِّر',
    subTitle: 'The Cloaked',
    pageStart: 575,
    pageEnd: 577,
    madani: 0,
  },
  {
    labelEng: 'Al-Qiyamah',
    labelAra: 'سُوْرَۃُ القِيَامَة',
    subTitle: 'The Resurrection',
    pageStart: 577,
    pageEnd: 578,
    madani: 0,
  },
  {
    labelEng: 'Ad-Dahr',
    labelAra: 'سُوْرَۃُ الإِنْسَان',
    subTitle: 'The Human',
    pageStart: 578,
    pageEnd: 580,
    madani: 1,
  },
  {
    labelEng: 'Al-Mursalat',
    labelAra: 'سُوْرَۃُ المُرْسَلَات',
    subTitle: 'Those Sent Forth',
    pageStart: 580,
    pageEnd: 581,
    madani: 0,
  },
  {
    labelEng: 'An-Naba’',
    labelAra: 'سُوْرَۃُ النَّبَأ',
    subTitle: 'The Great News',
    pageStart: 582,
    pageEnd: 583,
    madani: 0,
  },
  {
    labelEng: 'An-Nazi’at',
    labelAra: 'سُوْرَۃُ النَّازِعَات',
    subTitle: 'Those Who Pull Out',
    pageStart: 583,
    pageEnd: 584,
    madani: 0,
  },
  {
    labelEng: '‘Abasa',
    labelAra: 'سُوْرَۃ عَبَسَ',
    subTitle: 'He Frowned',
    pageStart: 585,
    pageEnd: 585,
    madani: 0,
  },
  {
    labelEng: 'At-Takwir',
    labelAra: 'سُوْرَۃُ التَّكْوِير',
    subTitle: 'The Overthrowing',
    pageStart: 586,
    pageEnd: 586,
    madani: 0,
  },
  {
    labelEng: 'Al-Infitar',
    labelAra: 'سُوْرَۃُ الإِنْفِطَار',
    subTitle: 'The Cleaving',
    pageStart: 587,
    pageEnd: 587,
    madani: 0,
  },
  // kr dia is sy nichy
  {
    labelEng: 'Al-Mutaffifin',
    labelAra: 'سُوْرَۃُ المُطَفِّفِين',
    subTitle: 'Those Who Deal in Fraud',
    pageStart: 587,
    pageEnd: 589,
    madani: 0,
  },
  {
    labelEng: 'Al-Inshiqaq',
    labelAra: 'سُوْرَۃُ الإِنْشِقَاق',
    subTitle: 'The Splitting Asunder',
    pageStart: 589,
    pageEnd: 589,
    madani: 0,
  },
  {
    labelEng: 'Al-Buruj',
    labelAra: 'سُوْرَۃُ البُرُوج',
    subTitle: 'The Stars',
    pageStart: 590,
    pageEnd: 590,
    madani: 0,
  },
  {
    labelEng: 'At-Tariq',
    labelAra: 'سُوْرَۃُ الطَّارِق',
    subTitle: 'The Nightcomer',
    pageStart: 590,
    pageEnd: 591,
    madani: 0,
  },
  {
    labelEng: 'Al-A’la',
    labelAra: 'سُوْرَۃُ الأَعْلَىٰ',
    subTitle: 'The Most High',
    pageStart: 591,
    pageEnd: 592,
    madani: 0,
  },
  {
    labelEng: 'Al-Ghashiyah',
    labelAra: 'سُوْرَۃُ الغَاشِيَة',
    subTitle: 'The Overwhelming',
    pageStart: 592,
    pageEnd: 592,
    madani: 0,
  },
  {
    labelEng: 'Al-Fajr',
    labelAra: 'سُوْرَۃُ الفَجْر',
    subTitle: 'The Dawn',
    pageStart: 593,
    pageEnd: 594,
    madani: 0,
  },
  {
    labelEng: 'Al-Balad',
    labelAra: 'سُوْرَۃُ البَلَد',
    subTitle: 'The City',
    pageStart: 594,
    pageEnd: 594,
    madani: 0,
  },
  {
    labelEng: 'Ash-Shams',
    labelAra: 'سُوْرَۃُ الشَّمْس',
    subTitle: 'The Sun',
    pageStart: 594,
    pageEnd: 595,
    madani: 0,
  },
  {
    labelEng: 'Al-Layl',
    labelAra: 'سُوْرَۃُ اللَّيْل',
    subTitle: 'The Night',
    pageStart: 595,
    pageEnd: 596,
    madani: 0,
  },
  {
    labelEng: 'Adh-Dhuha',
    labelAra: 'سُوْرَۃُ الضُّحَىٰ',
    subTitle: 'The Forenoon',
    pageStart: 596,
    pageEnd: 596,
    madani: 0,
  },
  {
    labelEng: 'Al-Inshirah',
    labelAra: 'سُوْرَۃُ الشَّرْح',
    subTitle: 'The Opening Forth',
    pageStart: 596,
    pageEnd: 596,
    madani: 0,
  },
  {
    labelEng: 'At-Tin',
    labelAra: 'سُوْرَۃُ التِّين',
    subTitle: 'The Fig',
    pageStart: 597,
    pageEnd: 597,
    madani: 0,
  },
  {
    labelEng: 'Al-‘Alaq',
    labelAra: 'سُوْرَۃُ العَلَق',
    subTitle: 'The Clot',
    pageStart: 597,
    pageEnd: 597,
    madani: 0,
  },
  {
    labelEng: 'Al-Qadar',
    labelAra: 'سُوْرَۃُ القَدْر',
    subTitle: 'The Night of Decree',
    pageStart: 598,
    pageEnd: 598,
    madani: 0,
  },
  {
    labelEng: 'Al-Bayinah',
    labelAra: 'سُوْرَۃُ البَيِّنَة',
    subTitle: 'The Proof',
    pageStart: 598,
    pageEnd: 599,
    madani: 1,
  },
  {
    labelEng: 'Az-Zalzalah',
    labelAra: 'سُوْرَۃُ الزَّلْزَلَة',
    subTitle: 'The Earthquake',
    pageStart: 599,
    pageEnd: 599,
    madani: 1,
  },
  {
    labelEng: 'Al-‘Adiyah',
    labelAra: 'سُوْرَۃُ العَادِيَات',
    subTitle: 'The Runners',
    pageStart: 599,
    pageEnd: 600,
    madani: 0,
  },
  {
    labelEng: 'Al-Qari’ah',
    labelAra: 'سُوْرَۃُ القَارِعَة',
    subTitle: 'The Striking Hour',
    pageStart: 600,
    pageEnd: 600,
    madani: 0,
  },
  {
    labelEng: 'At-Takathur',
    labelAra: 'سُوْرَۃُ التَّكَاثُر',
    subTitle: 'The Piling Up',
    pageStart: 600,
    pageEnd: 600,
    madani: 0,
  },
  {
    labelEng: 'Al-‘Asr',
    labelAra: 'سُوْرَۃُ العَصْر',
    subTitle: 'the Time',
    pageStart: 601,
    pageEnd: 601,
    madani: 0,
  },
  {
    labelEng: 'Al-Humazah',
    labelAra: 'سُوْرَۃُ الهُمَزَة',
    subTitle: 'The Slanderer',
    pageStart: 601,
    pageEnd: 601,
    madani: 0,
  },
  {
    labelEng: 'Al-Fil',
    labelAra: 'سُوْرَۃُ الفِيل',
    subTitle: 'The Elephant',
    pageStart: 601,
    pageEnd: 601,
    madani: 0,
  },
  {
    labelEng: 'Quraish',
    labelAra: 'سُوْرَۃ قُرَيْش',
    subTitle: 'Quraish',
    pageStart: 602,
    pageEnd: 602,
    madani: 0,
  },
  {
    labelEng: 'Al-Ma’un',
    labelAra: 'سُوْرَۃُ المَاعُون',
    subTitle: 'The Assistance',
    pageStart: 602,
    pageEnd: 602,
    madani: 0,
  },
  {
    labelEng: 'Al-Kauthar',
    labelAra: 'سُوْرَۃُ الكَوْثَر',
    subTitle: 'The River of Abundance',
    pageStart: 602,
    pageEnd: 602,
    madani: 0,
  },
  {
    labelEng: 'Al-Kafirun',
    labelAra: 'سُوْرَۃُ الكَافِرُون',
    subTitle: 'The Disbelievers',
    pageStart: 603,
    pageEnd: 637,
    madani: 0,
  },
  {
    labelEng: 'An-Nasr',
    labelAra: 'سُوْرَۃُ النَّصْر',
    subTitle: 'The Help',
    pageStart: 603,
    pageEnd: 603,
    madani: 1,
  },
  {
    labelEng: 'Al-Masad',
    labelAra: 'سُوْرَۃُ المَسَد',
    subTitle: 'The Palm Fiber',
    pageStart: 603,
    pageEnd: 603,
    madani: 0,
  },
  {
    labelEng: 'Al-Ikhlas',
    labelAra: 'سُوْرَۃُ الإِخْلَاص',
    subTitle: 'The Sincerity',
    pageStart: 604,
    pageEnd: 604,
    madani: 0,
  },
  {
    labelEng: 'Al-Falaq',
    labelAra: 'سُوْرَۃُ الفَلَق',
    subTitle: 'The Daybreak',
    pageStart: 604,
    pageEnd: 604,
    madani: 0,
  },
  {
    labelEng: 'An-Nas',
    labelAra: 'سُوْرَۃُ النَّاس',
    subTitle: 'Mankind',
    pageStart: 604,
    pageEnd: 604,
    madani: 0,
  },
];
